- name: Import the public key used by the package management system
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc
    state: present

- name: Import Mongodb Repo
  shell: |
    echo deb [ arch=amd64,arm64,s390x ] https://repo.mongodb.{{mongodb_dns_endstr}}/apt/ubuntu {{ansible_distribution_release}}/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}} multiverse > /etc/apt/sources.list.d/mongodb-{{mongodb_cmd_endstr}}-{{mongodb_version}}.list

- name: Install Mongodb 
  apt:
    name: mongodb-{{mongodb_cmd_endstr}}
    update_cache: yes
    allow_unauthenticated: yes

- name: mongodb tmpfiles.d
  shell: |
    echo 'd /var/run/mongodb/ 0755 mongodb mongodb' > /etc/tmpfiles.d/mongodb.conf
    systemd-tmpfiles --create

- name: Create Databases Directory
  file:
    path: /data/mongo
    state: directory
    owner: mongodb
    group: mongodb
    
- name: Add soft link for Mongod service
  shell: |
    ln -sb /lib/systemd/system/mongo.service  /lib/systemd/system/mongod.service
    ln -sb /lib/systemd/system/mongo.service  /lib/systemd/system/mongodb.service
