- name: Import the public key used by the package management system
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc
    state: present

- name: Import Mongodb Repo
  shell: |
    echo deb [ arch=amd64,arm64,s390x ] https://repo.mongodb.{{mongodb_dns_endstr}}/apt/ubuntu {{ansible_distribution_release}}/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}} multiverse > /etc/apt/sources.list.d/mongodb-{{mongodb_cmd_endstr}}-{{mongodb_version}}.list

- name: Remove package
  apt:
    name: mongodb-{{mongodb_cmd_endstr}}
    state: absent
    
- name: Install Mongodb 
  shell: apt install mongodb-{{mongodb_cmd_endstr}} -y

- name: mongodb tmpfiles.d
  shell: |
    echo 'd /var/run/mongodb/ 0755 mongodb mongodb' > /etc/tmpfiles.d/mongodb.conf
    systemd-tmpfiles --create

- name: Create  Directory
  file:
    path: /data/mongodb
    state: directory
    owner: mongodb
    group: mongodb
