---
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install pymongo
  pip:
    name: pymongo

- name: Copy MongoDB Configuration
  copy: 
    src: mongod.conf
    dest: /etc/

- name: Clean
  shell: rm -rf /data/mongo/*

- name: Start MongoDB
  service:
    name:  mongod
    enabled: yes 
    state: started 

- name: Setting MongoDB Administrator User
  mongodb_user:
    database: admin
    name: root
    password: '{{mongodb_root_password}}'
    roles: root
    state: present

- name: Enable MongoDB authorization
  lineinfile:
    path: /etc/mongod.conf
    regexp: '  authorization: disabled'
    line: '  authorization: enabled'

- name: restart MongoDB
  service: name=mongod state=restarted enabled=yes

- name: Add soft link for Mongod directory
  shell: |
    ln -sb /etc/mongod.conf  /data/config/mongod.conf
    ln -sb /var/log/mongodb  /data/logs/mongodb

# display version and service state of components
- name: Get MongoDB version
  shell: sudo sh -c "mongo --version | grep MongoDB  1>> /data/logs/install_version.txt"

- name: Check MongoDB Service
  shell: systemctl status mongod | grep Active*
  register: check_mongodb_service
  notify: check_mongodb_service
