---
#1 pre-installation
- name: Install pymongo for Ansible MongoDB module
  pip:
    name: pymongo

- name: Remove the old data of MongoDB for re-install
  shell: |
    rm -rf /var/lib/mongo/*
    rm -rf /etc/mongod.conf
    
#2 install by OS family    
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

#3 configure     
- block: 
  - name: Restart MongoDB service
    service:
      name:  mongod
      state: restarted 

  - name: Setting MongoDB Administrator User
    mongodb_user:
      database: admin
      name: root
      password: '{{mongodb_root_password}}'
      roles: 'root'
      state: present
      update_password: always
   
  - name: Enable MongoDB authorization
    blockinfile:
      path: /etc/mongod.conf
      insertafter: "#security:"
      block: |
        security:
          authorization: enabled
          
  when: mongodb_authentication

- block:
  - name: Enable MongoDB remote connection
    replace:
      path: /etc/mongod.conf
      regexp: 'bindIp: 127.0.0.1'
      replace: 'bindIp: 0.0.0.0'
      
  when: mongodb_remote

- name: Start and enable MongoDB service
  service:
    name:  mongod
    enabled: yes 
    
- name: Add soft link for Mongod directory
  shell: |
    ln -sb /etc/mongod.conf  /data/config/mongod.conf
    ln -sb /var/lib/mongo  /data/mongodb
    ln -sb /var/log/mongodb  /data/logs/mongodb

#5 display version and service state of components
- name: Get MongoDB version
  shell: sudo sh -c "mongo --version | grep MongoDB  1>> /data/logs/install_version.txt"

- name: Check MongoDB Service
  shell: systemctl status mongod | grep Active*
  register: check_mongodb_service
  notify: check_mongodb_service
