---
- set_fact:
    mongodb_cmd_endstr: "{{mongodb_server_meta[mongodb_server].name}}"
    mongodb_url_endstr: "{{mongodb_server_meta[mongodb_server].url}}"
    mongodb_dns_endstr: "{{mongodb_server_meta[mongodb_server].dns}}"
    
- set_fact:
    mongodb_baseurl: https://repo.mongodb.{{mongodb_dns_endstr}}/yum/redhat/$releasever/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}}/{{mongodb_url_endstr}}/
  when: ansible_distribution != 'Amazon'

- set_fact:
    mongodb_baseurl: https://repo.mongodb.{{mongodb_dns_endstr}}/yum/amazon/2/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}}/{{mongodb_url_endstr}}/
  when: ansible_distribution == 'Amazon'

- name: Yum configure the MongdoDB -{{mongodb_server}}-{{mongodb_version}}
  yum_repository:
    name: mongodb-{{mongodb_cmd_endstr}}-{{mongodb_version}}
    description: mongodb {{mongodb_server}} {{mongodb_version}}
    file: mongodb-{{mongodb_cmd_endstr}}-{{mongodb_version}}
    baseurl: "{{mongodb_baseurl}}"
    gpgkey: https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc
    gpgcheck: yes
    enabled: yes

- name: Yum install MongdoDB
  yum: 
    name: mongodb-{{mongodb_cmd_endstr}}
    state: latest
    
- name: Create Databases Directory
  file:
    path: /data/mongo
    state: directory
    owner: mongod
    group: mongod
    
- name: Add soft link for Mongod service
  shell: |
    ln -sb /usr/lib/systemd/system/mongod.service  /usr/lib/systemd/system/mongo.service
    ln -sb /usr/lib/systemd/system/mongod.service  /usr/lib/systemd/system/mongodb.service
