---
- set_fact:
    mongodb_baseurl: https://repo.mongodb.{{mongodb_dns_endstr}}/yum/redhat/$releasever/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}}/{{mongodb_url_endstr}}/
  when: ansible_distribution != 'Amazon'

- set_fact:
    mongodb_baseurl: https://repo.mongodb.{{mongodb_dns_endstr}}/yum/amazon/2/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}}/{{mongodb_url_endstr}}/
  when: ansible_distribution == 'Amazon' and mongodb_version < "4.0"
 
- set_fact:
    mongodb_baseurl: https://repo.mongodb.{{mongodb_dns_endstr}}/yum/redhat/7/mongodb-{{mongodb_cmd_endstr}}/{{mongodb_version}}/{{mongodb_url_endstr}}/
  when: ansible_distribution == 'Amazon' and mongodb_version >= "4.0"

- name: Yum configure the MongdoDB -{{mongodb_server}}-{{mongodb_version}}
  yum_repository:
    name: mongodb-{{mongodb_cmd_endstr}}-{{mongodb_version}}
    description: mongodb {{mongodb_server}} {{mongodb_version}}
    file: mongodb-{{mongodb_cmd_endstr}}-{{mongodb_version}}
    baseurl: "{{mongodb_baseurl}}"
    gpgkey: https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc
    gpgcheck: yes
    enabled: yes

- name: Remove old package
  yum:
    name: mongodb-{{mongodb_cmd_endstr}}
    state: absent

- name: Yum install MongdoDB
  shell: yum install mongodb-{{mongodb_cmd_endstr}} -y
    
- name: Create Databases Directory /data/mongodb
  file:
    path: /data/mongodb
    state: directory
    owner: mongod
    group: mongod
    
- name: Create Databases Directory /data/db
  file:
    path: /data/db
    state: directory
    owner: mongod
    group: mongod
    
- name: Add soft link for Mongod service
  shell: |
    ln -sb /usr/lib/systemd/system/mongod.service  /usr/lib/systemd/system/mongo.service
    ln -sb /usr/lib/systemd/system/mongod.service  /usr/lib/systemd/system/mongodb.service
