---
- set fact:
    mongodb_baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{mongodb_version}}/x86_64/
  when: ansible_distribution != 'Amazon'

- set fact:
    mongodb_baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/{{mongodb_version}}/x86_64/
  when: ansible_distribution == 'Amazon'

- set fact:
    mongodb_cmd: "{{mongodb_server_meta[mongodb_server].name}}"
  when: ansible_distribution == 'Amazon'
  
- name: Yum Install the MongdoDB -{{mongodb_server}}-{{mongodb_version}}
  yum_repository:
    name: mongodb-{{mongodb_server}}-{{mongodb_version}}
    description: mongodb {{mongodb_server}} {{mongodb_version}}
    file: mongodb-org-{{mongodb_version}}
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{mongodb_version}}/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc
    gpgcheck: yes
    enabled: yes
  
- name: Install the repository RPM
  yum_repository:
    name: mongodb-org-{{mongodb_version}}
    description: mongodb {{mongodb_version}}
    file: mongodb-org-{{mongodb_version}}
    baseurl: https://repo.mongodb.org/yum/redhat/7/mongodb-org/{{mongodb_version}}/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc
    gpgcheck: yes
    enabled: yes
  when: ansible_distribution == 'Amazon'

- name: Install MongoDB{{mongodb_version}}
  yum: 
    name: [mongodb-org]
    state: latest
    
- name: Create Databases Directory
  file:
    path: /data/mongo
    state: directory
    owner: mongod
    group: mongod
    
- name: Add soft link for Mongod service
  shell: |
    ln -sb /usr/lib/systemd/system/mongod.service  /usr/lib/systemd/system/mongo.service
    ln -sb /usr/lib/systemd/system/mongod.service  /usr/lib/systemd/system/mongodb.service
